### ISSUE TITLE
Free memory

### ISSUE THREAD

**Issue by HamedMasafi** [aDota2Player/Engine#4]
https://github.com/aDota2Player/Engine/blob/077f18e83176d3c2e547f38dd611af7b0a29bc2f/Lonely/Lonely-core/ExampleGame/Game.cpp#L13

این کلاس چند آبجکت ایجاد کرده که در مخرب فضای اونها ازاد نشده. چند مورد که من سرسری دیدم اینا بودن:
m_Background 
m_Paddle 
m_Ball

**Comment by aDota2Player** [comment]
گیم بشتر برای تست کردن بود چیزی نیست که تو انجین بمونه . درستش کردم به هر حال
